import { useEffect, useState } from 'react';
import { api, getApiError, isUnauthenticated } from '../services/api';
type Row={itemId:number;name:string;unit:string;quantity:number;isDemo:boolean;method:string;calendarNote:string;weekendRatio:number|null;recommendation:{orderDate:string;arrivalDate:string;quantity:number|null;urgent:boolean}|null;daily:{date:string;weekday:number;expectedSales:number|null}[]};
const dateLabel=(date:string)=>date.split('-').reverse().join('/');
export default function SalesCalendar({revision,onLogout,onChat}:{revision:number;onLogout:()=>void;onChat:()=>void}) {
 const [lead,setLead]=useState(2),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[assumptions,setAssumptions]=useState('');
 const [filter,setFilter]=useState(false);
 useEffect(()=>{
  let active=true;
  api.get(`/advisor/calendar?leadDays=${lead}`).then(({data})=>{if(active){setRows(data.items);setAssumptions(data.assumptions);setError('');}}).catch(e=>{if(active){setRows([]);setError(getApiError(e));if(isUnauthenticated(e))onLogout();}}).finally(()=>{if(active)setLoading(false);});
  return()=>{active=false;};
 },[lead,revision,onLogout]);
 const visible=rows.filter(r=>!filter||r.recommendation).sort((a,b)=>(a.recommendation?.orderDate??'9999').localeCompare(b.recommendation?.orderDate??'9999'));
 return <section className="dashboard-card restock-card"><div className="card-heading"><div><span className="section-kicker">CHUẨN BỊ TRƯỚC 14 NGÀY</span><h2>Lịch nhập dự kiến</h2></div><button className="inventory-refresh" onClick={onChat}>Hỏi trợ lý</button></div><p className="restock-explanation">Tính ngày cần hàng từ tồn kho và lịch sử bán. Chỉ dùng xu hướng theo thứ khi có ít nhất 4 tuần đầy đủ; lịch sử ít hơn sẽ dùng mức bán trung bình. Đây là ước tính, không phải đơn đặt hàng.</p><div className="restock-controls"><label>Nhà cung cấp giao sau<select value={lead} onChange={e=>{setLead(Number(e.target.value));setLoading(true);}}>{Array.from({length:15},(_,i)=><option key={i} value={i}>{i} ngày</option>)}</select></label><label><input type="checkbox" checked={filter} onChange={e=>setFilter(e.target.checked)}/> Chỉ hàng có đề xuất nhập</label></div>{error&&<p role="alert" className="restock-error">{error}</p>}{loading?<p role="status">Đang tính lịch nhập…</p>:<><div className="restock-table-wrap"><table className="restock-table"><thead><tr><th>Sản phẩm</th><th>Nên đặt ngày</th><th>Cần hàng ngày</th><th>Lượng nhập</th><th>Cơ sở</th></tr></thead><tbody>{visible.map(item=><tr key={item.itemId}><td><strong>{item.name}</strong><small>Tồn {item.quantity} {item.unit}</small>{item.isDemo&&<small>Dữ liệu giả lập để test</small>}</td><td>{item.recommendation?dateLabel(item.recommendation.orderDate):'—'}{item.recommendation?.urgent&&<small>Cần giao gấp / kiểm tra nhà cung cấp</small>}</td><td>{item.recommendation?dateLabel(item.recommendation.arrivalDate):'—'}</td><td>{item.recommendation?`${item.recommendation.quantity??'Cần kiểm tra'} ${item.unit}`:item.method==='INSUFFICIENT'?'Chưa đủ dữ liệu':'Chưa cần trong 14 ngày'}</td><td>{item.method==='WEEKDAY'?'Theo thứ trong tuần':item.method==='AVERAGE'?'Trung bình ngày':'Chưa đủ dữ liệu'}{item.weekendRatio!==null&&<small>Cuối tuần/ngày thường: {item.weekendRatio} lần</small>}<details><summary>Xem 14 ngày</summary><p>{item.calendarNote}</p>{item.daily.map(day=><p key={day.date}>{['CN','T2','T3','T4','T5','T6','T7'][day.weekday]} {dateLabel(day.date)}: {day.expectedSales===null?'Chưa ước tính':`≈ ${day.expectedSales} ${item.unit}`}</p>)}</details></td></tr>)}</tbody></table></div>{!visible.length&&<p>Chưa có mặt hàng phù hợp.</p>}<p className="restock-explanation">{assumptions}</p><p className="restock-explanation">Hạn gần nhất được áp dụng cho cả mặt hàng. Kiểm tra lô hàng, số tồn thực tế và xác nhận với nhà cung cấp trước khi đặt.</p></>}</section>;
}
