import { useEffect, useRef, type ReactNode } from 'react';
const labels: Record<string, string> = { ACTIVE: 'Hoạt động', SUSPENDED: 'Khóa tạm', BANNED: 'Khóa vĩnh viễn', DRAFT: 'Chưa gửi duyệt', PENDING: 'Chờ duyệt', APPROVED: 'Đã xác minh', REJECTED: 'Cần bổ sung', PAID: 'Đã thu', UNPAID: 'Chưa thu', NO_FEE: 'Miễn phí', UNTRACKED: 'Thiếu dữ liệu', SUCCESS: 'Thành công', ERROR: 'Lỗi / dự phòng', STARTED: 'Chưa kết thúc', STORE_OWNER: 'Chủ tạp hóa', SUPPLIER: 'Chủ vựa' };
export function Badge({ status }: { status: string }) { return <span className={`admin-badge ${['ACTIVE', 'APPROVED', 'PAID', 'SUCCESS'].includes(status) ? 'good' : ['BANNED', 'ERROR'].includes(status) ? 'bad' : ''}`}>{labels[status] || status}</span>; }
export function Metric({ label, value, note }: { label: string; value: ReactNode; note?: string }) { return <article className="admin-metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</article>; }
export function Empty({ children = 'Chưa có dữ liệu phù hợp với bộ lọc.' }: { children?: ReactNode }) { return <div className="admin-empty"><span aria-hidden="true">◌</span><p>{children}</p></div>; }
export function LoadState({ loading, error }: { loading: boolean; error?: string }) { return loading ? <p className="admin-loading" role="status">Đang lấy dữ liệu…</p> : error ? <p className="error-notice" role="alert">{error}</p> : null; }
export function Pager({ page, total, hasMore, onPage }: { page: number; total: number; hasMore: boolean; onPage: (page: number) => void }) { return <div className="admin-pager"><span>{total.toLocaleString('vi-VN')} kết quả · Trang {page}</span><div><button disabled={page <= 1} onClick={() => onPage(page - 1)}>← Trước</button><button disabled={!hasMore} onClick={() => onPage(page + 1)}>Sau →</button></div></div>; }
export function DateFields({ value, onChange }: { value: { from: string; to: string }; onChange: (value: { from: string; to: string }) => void }) { return <><label>Từ ngày<input type="date" required value={value.from} max={value.to} onChange={e => onChange({ ...value, from: e.target.value })} /></label><label>Đến ngày<input type="date" required min={value.from} value={value.to} onChange={e => onChange({ ...value, to: e.target.value })} /></label></>; }
export function AdminDialog({ title, children, busy, onClose }: { title: string; children: ReactNode; busy: boolean; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; const focus = document.activeElement as HTMLElement | null; dialog?.showModal(); return () => { dialog?.close(); focus?.focus(); }; }, []);
  return <dialog ref={ref} className="admin-dialog" aria-labelledby="admin-dialog-title" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><div className="admin-dialog-heading"><h2 id="admin-dialog-title">{title}</h2><button type="button" aria-label="Đóng" disabled={busy} onClick={onClose}>×</button></div>{children}</dialog>;
}
